name: autofix.ci # Needed to securely identify the workflow

on:
  push:    # Will trigger on pushes to all branches
  pull_request:  # Will trigger for pull requests targeting all branches

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4 # Updated to use the latest version

      # Setup Node.js and cache npm dependencies
      - uses: actions/setup-node@v4 # Updated version
        with:
          node-version: 20.5
          cache: 'npm' # Caching npm dependencies

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Lint & Fix
      - name: Lint & Fix
        run: npm run lint:fix

      # Autofix CI step
      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c